runtime: python39

service: frontend-service
entrypoint: chainlit run st.py --host 0.0.0.0 --port $PORT

instance_class: F2

env_variables:
  API_URL: "https://backend-service-dot-YOUR_PROJECT_ID.uc.r.appspot.com/query/"
  HISTORY_URL: "https://backend-service-dot-YOUR_PROJECT_ID.uc.r.appspot.com/history/"
  CLEAR_HISTORY_URL: "https://backend-service-dot-YOUR_PROJECT_ID.uc.r.appspot.com/clear_history/"
  PORT: "8080"

handlers:
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 3
  target_cpu_utilization: 0.65 